In [2]:
import pandas as pd

# Specify the path to your .tab file
file_path = 'events.2022.20230106.tab'

# Use pandas to read the .tab file
df = pd.read_csv(file_path, delimiter='\t')

# Display the DataFrame
df

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

FileNotFoundError: [Errno 2] No such file or directory: 'events.2022.20230106.tab'

In [16]:
print(df.columns)

Index(['Event ID', 'Event Date', 'Source Name', 'Source Sectors',
       'Source Country', 'Event Text', 'CAMEO Code', 'Intensity',
       'Target Name', 'Target Sectors', 'Target Country', 'Story ID',
       'Sentence Number', 'Publisher', 'City', 'District', 'Province',
       'Country', 'Latitude', 'Longitude'],
      dtype='object')

In [17]:
unique_countries = df['Source Name'].unique()


print(unique_countries)

['South Korea' 'Ministry (Indonesia)' 'Denis Moncada' ... 'Audi'
 'Political Parties (Myanmar)' 'Song Qingling']

In [18]:
# East Asia and US
selected_countries = ['China', 'Hong Kong', 'Macau', 'Japan', 'Mongolia', 'North Korea', 'South Korea', 'Taiwan', 'United States']

filtered_df = df[df['Source Name'].isin(selected_countries)]
filtered_df

,Event ID,Event Date,Source Name,Source Sectors,Source Country,Event Text,CAMEO Code,Intensity,Target Name,Target Sectors,Target Country,Story ID,Sentence Number,Publisher,City,District,Province,Country,Latitude,Longitude
0,36615529,2022-01-01,South Korea,NaN,South Korea,Demand rights,1043,-5.0,Government (South Korea),Government,South Korea,54339603,2,Yonhap English News,Seoul,NaN,Seoul-teukbyeolsi,South Korea,37.5683,126.97800
4,36615523,2022-01-01,China,NaN,China,Make a visit,42,1.9,Denis Moncada,"Executive,Foreign Ministry,Government",Nicaragua,54339617,1,Al Jazeera English,Managua,NaN,Departamento de Managua,Nicaragua,12.1328,-86.25040
5,36615522,2022-01-01,China,NaN,China,Grant diplomatic recognition,54,6.0,Nicaragua,NaN,Nicaragua,54339617,3,Al Jazeera English,Beijing,NaN,Beijing Shi,China,39.9075,116.39700
14,36615535,2022-01-01,United States,NaN,United States,Meet at a 'third' location,44,2.5,Russia,NaN,Russian Federation,54339646,2,Associated Press Newswires,Geneve,NaN,Canton de Geneve,Switzerland,46.2022,6.14569
26,36615556,2022-01-01,Taiwan,NaN,Taiwan,Make an appeal or request,20,3.0,China,NaN,China,54339779,4,Central News Agency English News,Beijing,NaN,Beijing Shi,China,39.9075,116.39700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796843,37530662,2022-12-31,Japan,NaN,Japan,Host a visit,43,2.8,G7,"Global,Global Economic/Financial/Trade IGOs,In...",NaN,56602761,5,Kyodo News,Hiroshima,NaN,Hiroshima-ken,Japan,34.3963,132.45900
796889,37530753,2022-12-31,United States,NaN,United States,Assassinate,186,-10.0,Qasem Soleimani,"Government,Military",Iran,56602876,6,FARS News Agency,Tehran,NaN,Tehran Province,Iran,35.6944,51.42150
796901,37530701,2022-12-31,United States,NaN,United States,Host a visit,43,2.8,Jair Bolsonaro,"Elite,Executive,Executive Office,Government",Brazil,56602903,6,Agence France-Presse,NaN,NaN,Florida,United States,28.7505,-82.50010
796906,37533059,2022-12-31,United States,NaN,United States,Host a visit,43,2.8,Jair Bolsonaro,"Elite,Executive,Executive Office,Government",Brazil,56610049,3,El Nacional,NaN,NaN,NaN,United States,38.8951,-77.03640
796911,37534174,2022-12-31,South Korea,NaN,South Korea,Accuse,112,-2.0,North Korea,NaN,North Korea,56612074,2,United News of Bangladesh Limited,Pyongyang,NaN,P'yongyang-si,North Korea,39.0339,125.75400

In [19]:
# Target country
filtered_df2 = filtered_df[filtered_df['Target Country'].isin(selected_countries)]
filtered_df2

,Event ID,Event Date,Source Name,Source Sectors,Source Country,Event Text,CAMEO Code,Intensity,Target Name,Target Sectors,Target Country,Story ID,Sentence Number,Publisher,City,District,Province,Country,Latitude,Longitude
0,36615529,2022-01-01,South Korea,NaN,South Korea,Demand rights,1043,-5.0,Government (South Korea),Government,South Korea,54339603,2,Yonhap English News,Seoul,NaN,Seoul-teukbyeolsi,South Korea,37.5683,126.9780
26,36615556,2022-01-01,Taiwan,NaN,Taiwan,Make an appeal or request,20,3.0,China,NaN,China,54339779,4,Central News Agency English News,Beijing,NaN,Beijing Shi,China,39.9075,116.3970
67,36615614,2022-01-01,China,NaN,China,Express intent to engage in diplomatic coopera...,32,4.5,Citizen (China),"General Population / Civilian / Social,Social",China,54339935,5,Unknown,Beijing,NaN,Beijing Shi,China,39.9075,116.3970
304,36615890,2022-01-01,Taiwan,NaN,Taiwan,Make an appeal or request,20,3.0,China,NaN,China,54340612,3,Taipei Times,Taipei,NaN,Taipei,Taiwan,25.0478,121.5320
338,36615935,2022-01-01,United States,NaN,United States,Make an appeal or request,20,3.0,Taiwan,NaN,Taiwan,54340709,6,South China Morning Post,NaN,NaN,Washington D.C.,United States,38.9171,-77.0003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796806,37530619,2022-12-31,North Korea,NaN,North Korea,Demonstrate military or police power,150,-7.2,Japan,NaN,Japan,56602676,1,Jiji Press English News Service,Seoul,NaN,Seoul-teukbyeolsi,South Korea,37.5683,126.9780
796807,37530620,2022-12-31,North Korea,NaN,North Korea,fight with artillery and tanks,194,-10.0,Japan,NaN,Japan,56602676,5,Jiji Press English News Service,Seoul,NaN,Seoul-teukbyeolsi,South Korea,37.5683,126.9780
796832,37530671,2022-12-31,China,NaN,China,Criticize or denounce,111,-2.0,Taiwan,NaN,Taiwan,56602723,6,Reuters News,Beijing,NaN,Beijing Shi,China,39.9075,116.3970
796833,37530672,2022-12-31,Taiwan,NaN,Taiwan,Accuse,112,-2.0,China,NaN,China,56602723,6,Reuters News,Beijing,NaN,Beijing Shi,China,39.9075,116.3970
796911,37534174,2022-12-31,South Korea,NaN,South Korea,Accuse,112,-2.0,North Korea,NaN,North Korea,56612074,2,United News of Bangladesh Limited,Pyongyang,NaN,P'yongyang-si,North Korea,39.0339,125.7540

In [21]:
# change to date type
filtered_df2['Event Date'] = pd.to_datetime(filtered_df2['Event Date'])

# "Month"
filtered_df2['Month'] = filtered_df2['Event Date'].dt.month

filtered_df2

/var/folders/m3/k788kw6103zdvc0bwpc1lzd00000gn/T/ipykernel_34593/4170864937.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df2['Event Date'] = pd.to_datetime(filtered_df2['Event Date'])
/var/folders/m3/k788kw6103zdvc0bwpc1lzd00000gn/T/ipykernel_34593/4170864937.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df2['Month'] = filtered_df2['Event Date'].dt.month

,Event ID,Event Date,Source Name,Source Sectors,Source Country,Event Text,CAMEO Code,Intensity,Target Name,Target Sectors,...,Story ID,Sentence Number,Publisher,City,District,Province,Country,Latitude,Longitude,Month
0,36615529,2022-01-01,South Korea,NaN,South Korea,Demand rights,1043,-5.0,Government (South Korea),Government,...,54339603,2,Yonhap English News,Seoul,NaN,Seoul-teukbyeolsi,South Korea,37.5683,126.9780,1
26,36615556,2022-01-01,Taiwan,NaN,Taiwan,Make an appeal or request,20,3.0,China,NaN,...,54339779,4,Central News Agency English News,Beijing,NaN,Beijing Shi,China,39.9075,116.3970,1
67,36615614,2022-01-01,China,NaN,China,Express intent to engage in diplomatic coopera...,32,4.5,Citizen (China),"General Population / Civilian / Social,Social",...,54339935,5,Unknown,Beijing,NaN,Beijing Shi,China,39.9075,116.3970,1
304,36615890,2022-01-01,Taiwan,NaN,Taiwan,Make an appeal or request,20,3.0,China,NaN,...,54340612,3,Taipei Times,Taipei,NaN,Taipei,Taiwan,25.0478,121.5320,1
338,36615935,2022-01-01,United States,NaN,United States,Make an appeal or request,20,3.0,Taiwan,NaN,...,54340709,6,South China Morning Post,NaN,NaN,Washington D.C.,United States,38.9171,-77.0003,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796806,37530619,2022-12-31,North Korea,NaN,North Korea,Demonstrate military or police power,150,-7.2,Japan,NaN,...,56602676,1,Jiji Press English News Service,Seoul,NaN,Seoul-teukbyeolsi,South Korea,37.5683,126.9780,12
796807,37530620,2022-12-31,North Korea,NaN,North Korea,fight with artillery and tanks,194,-10.0,Japan,NaN,...,56602676,5,Jiji Press English News Service,Seoul,NaN,Seoul-teukbyeolsi,South Korea,37.5683,126.9780,12
796832,37530671,2022-12-31,China,NaN,China,Criticize or denounce,111,-2.0,Taiwan,NaN,...,56602723,6,Reuters News,Beijing,NaN,Beijing Shi,China,39.9075,116.3970,12
796833,37530672,2022-12-31,Taiwan,NaN,Taiwan,Accuse,112,-2.0,China,NaN,...,56602723,6,Reuters News,Beijing,NaN,Beijing Shi,China,39.9075,116.3970,12
796911,37534174,2022-12-31,South Korea,NaN,South Korea,Accuse,112,-2.0,North Korea,NaN,...,56612074,2,United News of Bangladesh Limited,Pyongyang,NaN,P'yongyang-si,North Korea,39.0339,125.7540,12

In [22]:
filtered_df2.to_csv('2022_geo_event_EA.csv', index=False)

In [9]:
# filter all year data
import pandas as pd

def process_event_data(file_path, output_csv_name='filtered_events.csv'):
    # Use pandas to read the .tab file
    df = pd.read_csv(file_path, delimiter='\t')

    # East Asia and US
    selected_countries = ['China', 'Hong Kong', 'Macau', 'Japan', 'Mongolia', 'North Korea', 'South Korea', 'Taiwan', 'United States']

    # Filter by source name
    filtered_df = df[df['Source Name'].isin(selected_countries)]

    # Further filter by target country
    filtered_df2 = filtered_df[filtered_df['Target Country'].isin(selected_countries)]

    # Convert to date type
    filtered_df2['Event Date'] = pd.to_datetime(filtered_df2['Event Date'])

    # Extract the month
    filtered_df2['Month'] = filtered_df2['Event Date'].dt.month

    # Save as a CSV file
    filtered_df2.to_csv(output_csv_name, index=False)

# Specify the path to your .tab file
file_path = 'events.2012.20150313084811.tab'  # Update this with your file path
output_csv_name = '2012_geo_event_EA.csv'  # Update this with your desired output file name

# Call the function
process_event_data(file_path, output_csv_name)

/var/folders/m3/k788kw6103zdvc0bwpc1lzd00000gn/T/ipykernel_48986/876141439.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df2['Event Date'] = pd.to_datetime(filtered_df2['Event Date'])
/var/folders/m3/k788kw6103zdvc0bwpc1lzd00000gn/T/ipykernel_48986/876141439.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df2['Month'] = filtered_df2['Event Date'].dt.month

In [4]:
# merge data

import pandas as pd
from glob import glob

# Specify the pattern for matching the CSV files
file_pattern = '20*_geo_event_EA.csv'

# Use glob to get a list of file names matching the pattern
file_names = glob(file_pattern)

# Create an empty list to store DataFrames
dfs = []

# Loop through each file, read it as a DataFrame, and append to the list
for file in file_names:
    year = int(file[:4])  # Extract the year from the file name
    df = pd.read_csv(file)
    df['Year'] = year  # Add a 'Year' column
    dfs.append(df)

# Concatenate the list of DataFrames into a single DataFrame
merged_geo_event_data = pd.concat(dfs, ignore_index=True)

# Display the merged DataFrame
print(merged_geo_event_data.head())

# Save the merged DataFrame to a new CSV file if needed
merged_geo_event_data.to_csv('merged_geo_event_data.csv', index=False)

   Event ID  Event Date  Source Name  Source Sectors Source Country  \
0  33417401  2018-01-01  South Korea             NaN    South Korea
1  33417584  2018-01-01  North Korea             NaN    North Korea
2  33417316  2018-01-01  North Korea             NaN    North Korea
3  33417511  2018-01-01  South Korea             NaN    South Korea
4  33417390  2018-01-01  North Korea             NaN    North Korea

                        Event Text CAMEO Code  Intensity  \
0                Praise or endorse         51        3.4
1  Use conventional military force        190      -10.0
2  Use conventional military force        190      -10.0
3                Praise or endorse         51        3.4
4                         Threaten        130       -4.4

               Target Name                                     Target Sectors  \
0              Kim Jong-Un  (National) Major Party,Parties,Government Majo...
1  Citizen (United States)      Social,General Population / Civilian / Social
2  Citizen (United States)      Social,General Population / Civilian / Social
3              Kim Jong-Un  (National) Major Party,Parties,Government Majo...
4            United States                                                NaN

   ... Sentence Number                  Publisher         City District  \
0  ...               1               Reuters News  Pyeongchang      NaN
1  ...               4  Yogam Communications SARL    Pyongyang      NaN
2  ...               4  Yogam Communications SARL    Pyongyang      NaN
3  ...               1               Reuters News  Pyeongchang      NaN
4  ...               6         The New York Times          NaN      NaN

        Province        Country Latitude Longitude  Month  Year
0     Gangwon-do    South Korea  37.3703  128.3930      1  2018
1  P'yongyang-si    North Korea  39.0339  125.7540      1  2018
2  P'yongyang-si    North Korea  39.0339  125.7540      1  2018
3     Gangwon-do    South Korea  37.3703  128.3930      1  2018
4            NaN  United States  38.8951  -77.0364      1  2018

[5 rows x 22 columns]