In [2]:
import pandas as pd

# Specify the path to your .tab file
file_path = 'events.2022.20230106.tab'

# Use pandas to read the .tab file
df = pd.read_csv(file_path, delimiter='\t')

# Display the DataFrame
df

,Event ID,Event Date,Source Name,Source Sectors,Source Country,Event Text,CAMEO Code,Intensity,Target Name,Target Sectors,Target Country,Story ID,Sentence Number,Publisher,City,District,Province,Country,Latitude,Longitude
0,36615529,2022-01-01,South Korea,NaN,South Korea,Demand rights,1043,-5.0,Government (South Korea),Government,South Korea,54339603,2,Yonhap English News,Seoul,NaN,Seoul-teukbyeolsi,South Korea,37.56830,126.9780
1,36615519,2022-01-01,Ministry (Indonesia),Government,Indonesia,Reject,120,-4.0,Reuters,"Media,News,Social",United Kingdom,54339616,2,Unknown,Jakarta,NaN,Daerah Khusus Ibukota Jakarta,Indonesia,-6.21462,106.8450
2,36615520,2022-01-01,Denis Moncada,"Executive,Foreign Ministry,Government",Nicaragua,Host a visit,43,2.8,China,NaN,China,54339617,1,Al Jazeera English,Managua,NaN,Departamento de Managua,Nicaragua,12.13280,-86.2504
3,36615521,2022-01-01,Denis Moncada,"Executive,Foreign Ministry,Government",Nicaragua,Praise or endorse,51,3.4,Foreign Affairs (China),"Executive,Foreign Ministry,Government",China,54339617,1,Al Jazeera English,Managua,NaN,Departamento de Managua,Nicaragua,12.13280,-86.2504
4,36615523,2022-01-01,China,NaN,China,Make a visit,42,1.9,Denis Moncada,"Executive,Foreign Ministry,Government",Nicaragua,54339617,1,Al Jazeera English,Managua,NaN,Departamento de Managua,Nicaragua,12.13280,-86.2504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796912,37534173,2022-12-31,Joint Chiefs of Staff (South Korea),"Government,Military",South Korea,Make statement,10,0.0,South Korea,NaN,South Korea,56612074,3,United News of Bangladesh Limited,Pyongyang,NaN,P'yongyang-si,North Korea,39.03390,125.7540
796913,37533982,2022-12-31,Jamaat I Islami,"International Ethnic,International Religious,K...",NaN,Use conventional military force,190,-10.0,Police (Bangladesh),"Government,Police",Bangladesh,56612076,3,United News of Bangladesh Limited,Dhaka,Dhaka District,Dhaka Division,Bangladesh,23.71040,90.4074
796914,37534307,2022-12-31,Ministry (Bangladesh),Government,Bangladesh,Make an appeal or request,20,3.0,Political Parties (Bangladesh),Parties,Bangladesh,56612080,1,United News of Bangladesh Limited,Noakhali,NaN,Chittagong,Bangladesh,22.81760,91.0894
796915,37534306,2022-12-31,Ministry (Bangladesh),Government,Bangladesh,Make statement,10,0.0,Government (Bangladesh),Government,Bangladesh,56612080,5,United News of Bangladesh Limited,NaN,NaN,NaN,Bangladesh,23.71040,90.4074
796916,37534308,2022-12-31,Ministry (Bangladesh),Government,Bangladesh,"Defy norms, law",128,-5.0,Interim Government (Bangladesh),Government,Bangladesh,56612080,6,United News of Bangladesh Limited,NaN,NaN,NaN,Bangladesh,23.71040,90.4074